os: 
  #- osx
  - linux
language: go
go:
- '1.14'
before_install:
  - sudo apt-get -y install libxcursor-dev libx11-dev libxrandr-dev libxinerama-dev libxi-dev mesa-common-dev
before_deploy:
- "./hack/build-mac.sh"
- ls
- hdiutil create build/QRSecret.dmg -srcfolder build/QRSecret -ov
- ls build/
install: true

deploy:
  provider: releases
  api_key:
    secure: VMR3EMxcOVGUgKOHEumcqmXDWNMp8+bzCOeIBW1+HJAM1mtuuYRPIVlU6cBlSOjvO+v3dQ/wbooVc5sn5yrUnzhGfwdOFq+EUKFtTjRoSqKD9zFvcWFMlzX7kOtzVSFQLmjyrckYgEGjg5fKpjC5u9nZxoQhdqGEb4DA6Beivpz5WWNwJ9DuAp86jdYMeWD+fp6y9fmGKWLcfWDvlJTE2wSne6Om0RySiZigtP2um3oO/DvEvHYl3mFbqeobCMgtWyKLDz9doXCaatJ2vjNmmfgjr4WNyA9+y48q4wQlOZ7MgLP1OAI7aeD9TY9Wqs83lekEwlsEjDFaCnaUfW9c/hCKaNPZ9UYqi5hnlLvaQVxX7fzLH8OeZwC7Wyz/EiF/wOOfZrM0UiRmKEEY0w6ONJ/N2dDUhHZPQgEQaJUuDCk+Eaw/Q1rrXHkoVTPfR0OPkaiDDuGs4jsClYh65gpHsNniiuPFwry7Jl4rtvWR8F9regK/SDIEKQZGImHHJ2fN+rRDwgdD0cAP1uFEnXuo4U8HVggb/ZzJ1mHG+0PW43RNJ9yAgQiF9iGOtm3k92JqWGutlCzuqvWlAPGZ6zzRvGLxwsh5hcsng1V2ibZ0LimyPN/N2sGyf/ZnPnfj51jB2U1e8iVHmMI+39NBVZ1+PVudg7p2pe3NQ7LQt5LYNKY=
  file: build/QRSecret.dmg
  on:
    repo: pharmatics/qr-secret
    #tags: true
    #all_branches: true
  skip_cleanup: 'true'
