os: osx

language: go

go:
- '1.13'
- '1.14'
- 'tip'

before_deploy:
- ./hack/build-mac.sh
- ls
- hdiutil create build/QRSecret.dmg -srcfolder build/QRSecret -ov
- ls build/

install: true

deploy:
  provider: releases
  skip_cleanup: true
  #api_key:
    secure: 
  file: 
    - "dist/QRSecret.dmg"
  on:
    tags: true
    all_branches: true
    repo: pharmatics/qr-secret